
package com.ticketing.tqgisclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreateTicketImplService", targetNamespace = "http://webservice.view.TQGIS/", wsdlLocation = "http://127.0.0.1:7101/TQGIS/CreateTicketImplService?WSDL")
public class CreateTicketImplService
    extends Service
{

    private final static URL CREATETICKETIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREATETICKETIMPLSERVICE_EXCEPTION;
    private final static QName CREATETICKETIMPLSERVICE_QNAME = new QName("http://webservice.view.TQGIS/", "CreateTicketImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7101/TQGIS/CreateTicketImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATETICKETIMPLSERVICE_WSDL_LOCATION = url;
        CREATETICKETIMPLSERVICE_EXCEPTION = e;
    }

    public CreateTicketImplService() {
        super(__getWsdlLocation(), CREATETICKETIMPLSERVICE_QNAME);
    }

    public CreateTicketImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREATETICKETIMPLSERVICE_QNAME, features);
    }

    public CreateTicketImplService(URL wsdlLocation) {
        super(wsdlLocation, CREATETICKETIMPLSERVICE_QNAME);
    }

    public CreateTicketImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREATETICKETIMPLSERVICE_QNAME, features);
    }

    public CreateTicketImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateTicketImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreateTicketImpl
     */
    @WebEndpoint(name = "CreateTicketImplPort")
    public CreateTicketImpl getCreateTicketImplPort() {
        return super.getPort(new QName("http://webservice.view.TQGIS/", "CreateTicketImplPort"), CreateTicketImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateTicketImpl
     */
    @WebEndpoint(name = "CreateTicketImplPort")
    public CreateTicketImpl getCreateTicketImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.view.TQGIS/", "CreateTicketImplPort"), CreateTicketImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREATETICKETIMPLSERVICE_EXCEPTION!= null) {
            throw CREATETICKETIMPLSERVICE_EXCEPTION;
        }
        return CREATETICKETIMPLSERVICE_WSDL_LOCATION;
    }

}
