
package com.ticketing.tqgisclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreateTicketImpl", targetNamespace = "http://webservice.view.TQGIS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreateTicketImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startTicket", targetNamespace = "http://webservice.view.TQGIS/", className = "com.ticketing.tqgisclient.StartTicket")
    @ResponseWrapper(localName = "startTicketResponse", targetNamespace = "http://webservice.view.TQGIS/", className = "com.ticketing.tqgisclient.StartTicketResponse")
    @Action(input = "http://webservice.view.TQGIS/CreateTicketImpl/startTicketRequest", output = "http://webservice.view.TQGIS/CreateTicketImpl/startTicketResponse")
    public String startTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StartNewWorkflowInstance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StartNewWorkflowInstance", targetNamespace = "http://webservice.view.TQGIS/", className = "com.ticketing.tqgisclient.StartNewWorkflowInstance")
    @ResponseWrapper(localName = "StartNewWorkflowInstanceResponse", targetNamespace = "http://webservice.view.TQGIS/", className = "com.ticketing.tqgisclient.StartNewWorkflowInstanceResponse")
    @Action(input = "http://webservice.view.TQGIS/CreateTicketImpl/StartNewWorkflowInstanceRequest", output = "http://webservice.view.TQGIS/CreateTicketImpl/StartNewWorkflowInstanceResponse")
    public String startNewWorkflowInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

}
