package com.ag.generalsystemsapi.api.model.responses

import java.util.*

class ClinicalVisitResponse (
    var visitCode: Long? = null,
    var visitPatientCode: Long? = null,
    var visitPatientID: String? = null,
    var visitPatientName: String? = null,
    var visitPatientCover: String? = null,
    var visitPatientCoverWef: Date? = null,
    var visitPatientCoverWet: Date? = null,
    var visitInsuredName: String? = null,
    var visitInsuredTel: String? = null,
    var visitInsuredStatus: String? = null,
    var visitPatientCoverAmount: Double? = null,
    var visitTotalAmount: Double? = null,
    var visitInsuredAmount: Double? = null,
    var visitExcessAmount: Double? = null,
    var visitOrganizationCode: Long? = null,
    var visitOrganizationName: String? = null,
    var visitDate: Date? = null,
    var visitDetails: String? = null,
    var visitType: String? = null,
    var visitBillable: String? = null,
    var visitCurrentService: String? = null,
    var visitComplaints: String? = null,
    var visitExaminations: String? = null,
    var visitManagement: String? = null,
    var visitClinicalDiagnosis: String? = null,
    var visitFinalDiagnosis: String? = null,
    var visitStatus: String? = null,
    var petSchCode: Long? = null,
    var petSchAnimal: String? = null,
    var petSchBreed: String? = null,
    var petSchGender: String? = null,
    var petSchDOB: Date? = null,
    var petSchWeight: String? = null,
    var petSchMicrochipped: String? = null,
    var petSchMicroshipNo: String? = null,
    var petSchVaccinated: String? = null,
    var petSchMedicalConditions: String? = null,
    var petSchSurgeries: String? = null,
    var petSchMedications: String? = null,
    var petSchIllnessSign: String? = null,
    var petSchInjureOthers: String? = null,
    var petSchCommercial: String? = null,
    var petSchComments: String? = null,
    var petSchClinicName: String? = null,
    var petSchClinicTel: String? = null,
    var petSchClinicTown: String? = null,
    var clClaimCode: Long? = null,
    var clClaimDate: Date? = null,
    var clClaimAmount: Double? = null,
    var clClaimStatus: String? = null
)