package com.ag.generalsystemsapi.api.model.responses

import java.util.Date

class PolicyRiskResponse (
    var clientCode: Long? = null,
    var clientName: String? = null,
    var clientOtherNames: String? = null,
    var clientPIN: String? = null,
    var clientIdNumber: String? = null,
    var clientDateOfBirth: Date? = null,
    var clientGender: String? = null,
    var clientTelephone: String? = null,
    var clientPhysicalAddress: String? = null,
    var clientEmail: String? = null,
    var policyBatchNo: Long? = null,
    var policyNumber: String? = null,
    var policyProduct: String? = null,
    var policyCoverFromDate: Date? = null,
    var policyCoverToDate: Date? = null,
    var policyTotalSumInsured: Double? = null,
    var policyTotalNetPremium: Double? = null,
    var policyFrequencyOfPayment: String? = null,
    var policyStatus: String? = null,
    var policyRiskCode: Long? = null,
    var policyRiskPropertyID: String? = null,
    var policyRiskItemDesc: String? = null,
    var policyRiskBinder: String? = null,
    var policyRiskValue: Double? = null,
    var policyRiskBalance: Double? = null,
    var petSchCode: Long? = null,
    var petSchAnimal: String? = null,
    var petSchBreed: String? = null,
    var petSchGender: String? = null,
    var petSchDOB: Date? = null,
    var petSchWeight: String? = null,
    var petSchMicrochipped: String? = null,
    var petSchMicroshipNo: String? = null,
    var petSchVaccinated: String? = null,
    var petSchMedicalConditions: String? = null,
    var petSchSurgeries: String? = null,
    var petSchMedications: String? = null,
    var petSchIllnessSign: String? = null,
    var petSchInjureOthers: String? = null,
    var petSchCommercial: String? = null,
    var petSchComments: String? = null,
    var petSchClinicName: String? = null,
    var petSchClinicTel: String? = null,
    var petSchClinicTown: String? = null,
)